services:
  dash-rapido-araguaia-combustivel:
    build: .
    image: ceia-ufg/dash-rapido-araguaia-combustivel
    container_name: dash-rapido-araguaia-combustivel
    
    env_file:
      - src/.env
    
    ports:
      - "${PORT}:${PORT}"
    
    networks:
      - dash-rapido-araguaia-combustivel

    restart: unless-stopped

networks:
  dash-rapido-araguaia-combustivel:
    driver: bridge
